language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsforlabs
  api_key2:
    secure: wxI/iSl1A9IHZ969ndoLmYhN76vPhscpkJETB9zNtwuLsQN2GKeoo22oP+u2MXm84mA5Os0R7q06M01DWQ3fMujW/i1u1XzDXJXXdwuExbW/YO+5O/Z+Px0zYtWWlzFX+tAqya6N9QBdQIdsG9sday7Jlc3l3nTeeBy7i3BerLBhM+D+4xMWbxpzwzJ1AEV3hCudHVwgJQ2qofQAgmWMruzhUFyQdFAbXMk41nJpExQJHanyaPEy7ck+gOJ7ele9HC8pJJQJYIeqCYnByoXfJkWYEDXw4PrqrXkeHgeqGTpMgCk8EuPLJqLnkMuZ+TR/gfKso2WuhxocRnnkradWIcfQ5jl2/S5ueNwgie/Ino7K/Nbq+2X+RRe2h8dOkKSHCttjtBew9TWay7+azQxej9QkdYEMRnxqJSx0Yy5+EzOpfqjMe4sxqfvUU//i9vUFkuEjKIu7O0qi9R/F5Jk98M8LLiv+uTvUAzn/ZtR7vx6juMbo6AN7BVrhGPGk6+7AMZ+5zDvnnfSy1ku0OBO4LJ1jLN03ccc+Bv1R4dWOzJ3pAtIyUlUBJOSx7/f6ONlpP4o1n2PYbefxIW5nnn49yGc0gq5JqmXa3WiV/+Id7wj7Rja2ydaYJwYlIh2i1yUFbNKngNm9snFLFyuaeeIx2RCUIQ31yjlKT/QxwKzou5k=
